# Generated by Django 3.0.7 on 2020-08-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOTPVerificationLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTP', models.TextField()),
                ('mobileNo', models.CharField(max_length=10)),
                ('uid', models.TextField()),
            ],
        ),
    ]
