# Generated by Django 3.0.7 on 2020-08-10 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(max_length=100)),
                ('StoreAddress', models.TextField(max_length=100)),
                ('OwnerName', models.CharField(max_length=100)),
                ('OwnerNumber', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('Lat', models.CharField(blank=True, max_length=100)),
                ('Long', models.CharField(blank=True, max_length=100)),
                ('StoreImage', models.ImageField(upload_to='', verbose_name='photos/%Y/%m%d/')),
                ('IsVerified', models.BooleanField(default=True)),
                ('IsPublished', models.BooleanField(default=True)),
                ('ListingDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('IsKYCVerified', models.BooleanField(default=True)),
            ],
        ),
    ]
