# Generated by Django 3.0.7 on 2020-08-07 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='', verbose_name='photos/%Y/%m%d/')),
                ('address', models.TextField(max_length=100)),
                ('phone', models.IntegerField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('aadharNumber', models.IntegerField(max_length=20)),
                ('aadharImage', models.ImageField(upload_to='', verbose_name='photos/%Y/%m%d/')),
                ('licenseNumber', models.IntegerField(max_length=20)),
                ('ServicableAreaMin', models.IntegerField(max_length=20)),
                ('ServicableAreaMax', models.IntegerField(max_length=20)),
                ('is_loyal', models.BooleanField(default=True)),
                ('deliveryStatus', models.CharField(blank=True, max_length=50)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
