# Generated by Django 3.0.7 on 2020-08-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryPartner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypartner',
            name='ServicableAreaMax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='ServicableAreaMin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='aadharNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='licenseNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
